name: Orchestrator CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  call-test-workflow:
    name: 1. Run Tests
    uses: ./.github/workflows/sonarqube-action.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_ORG_KEY: ${{ secrets.SONAR_ORG_KEY }}

  call-build-workflow:
    name: 2. Build and Push Image
    needs: call-test-workflow
    
    if: github.event_name == 'push'
    uses: ./.github/workflows/docker-image.yml
    with:
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      CONTAINER_TAG_NAME: ${{ vars.CONTAINER_TAG_NAME }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
