name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
      - development

jobs:
  sonar_scan:
    name: Build and Analyze
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' 

      - name: Install Java for SonarScanner
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dotnet-sonarscanner global tool
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarQube Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        run: |
          export JAVA_HOME=$JAVA_HOME_17_X64
          
          dotnet sonarscanner begin \
            /k: "{{ secrets.SONAR_PROJECT_KEY }}" \
            /o:"{{ secrets.SONAR_ORG_KEY }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
            /d:sonar.solution="src/TeamManager.sln" \
            /d:sonar.scanner.skipJreProvisioning=true \
            /d:sonar.pullrequest.provider=github \
            /d:sonar.pullrequest.github.repository=${{ github.repository }} \
            /d:sonar.pullrequest.github.token.secured="${{ secrets.GITHUB_TOKEN }}" \
            /d:sonar.pullrequest.key=${{ github.event.pull_request.number }} \
            /d:sonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
          
      - name: Build .NET Project
        run: dotnet build "src/TeamManager.sln" --no-incremental
  
      - name: End SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}